Repository jorgeariasmartin/OceanLux-FrontEnd, pull requests merged in 2025-02, with the labels that each got.

#10 ✨ Feature/login&register
  public/login-bg.png
  src/app/app.routes.ts
  src/app/features/view-login-register/view-login-register.component.html
  src/app/features/view-login-register/view-login-register.component.ts
  src/app/model/User.ts
  src/app/services/auth.service.ts
  src/component/sidebar/sidebar.component.html
  src/component/sidebar/sidebar.component.ts
  src/styles.css
Labels: enhancement

#12 ✨ Feature/login&register
  src/app/features/view-login-register/view-login-register.component.html
  src/app/features/view-login-register/view-login-register.component.ts
  src/app/services/auth.service.ts
Labels: enhancement

#16 change loading styles and fix bugs before yachts administration
  src/app/features/admin-trips/admin-trips.component.ts
  src/app/services/auth.service.ts
  src/app/services/trip.service.ts
  src/component/loading/loading.component.html
Labels: bugfix, feature, refactor

#26 refactor code for admin ang loading styles
  src/app/features/admin-trips/admin-trips.component.html
  src/app/features/admin-trips/admin-trips.component.ts
  src/app/features/admin-yachts/admin-yachts.component.html
  src/app/features/admin-yachts/admin-yachts.component.ts
  src/app/model/yacht.ts
  src/component/loading/loading.component.html
Labels: refactor
